[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  # 将 node_modules 包含在 Functions 中
  included_files = ["node_modules/**"]

[context.production.environment]
  DB_TYPE = "postgresql"
  DATABASE_URL = "postgresql://postgres.vxsetefeaquvxbwarmis:tiaotiao2020@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
